// StageView — a 3D cutscene stage with color-coded skeleton actors performing
// REAL ARDY text-to-motion, importable props, a keyframed shot camera, and a raw
// 10s take recorded straight off the canvas.
//
// Actors are the ARDY Core (cskel27) skeleton, NOT finished characters: the raw
// take is a control video that an AI video pass uses to replace each actor.
// Motion is generated by the ARDY service (`/api/v1/motion/generate`) on that same
// skeleton, so frames apply with zero retargeting. A VRM can be attached to preview
// a skin, but it performs only when the retargeting path is available.
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { VRMLoaderPlugin, VRMUtils, type VRM } from "@pixiv/three-vrm";
import { TransformControls } from "three/examples/jsm/controls/TransformControls.js";
import { ACTOR_COLORS, HIP_HEIGHT, JOINTS, buildRig, type Rig } from "./ardySkeleton";
import { Prop, initPropLoader, isPropFile, loadProp, makeGltfLoader, type PropInfo } from "./props";
import { fetchMotionModels, generateMotion, uploadMedia, type Motion, type MotionConstraint, type UploadResponse } from "./api";
import type { PS } from "./shared";
import { enhanceMotionVideo, pickModel, type Artifact } from "./pipeline";
import { consumeCharacter } from "./characterHandoff";
import VrmPicker from "./VrmPicker";
import { registerActions } from "./control";
import { queueStudioAsset } from "./studioHandoff";
import "./stage.css";

const TAKE_SECONDS = 10; // matches the storyboard's default beat duration
const ARM_DOWN = 1.25; // rad — the rig rests in a T-pose; drop the arms for the idle pose
const CORE_FPS = 20; // ARDY `core` checkpoint fps (echoed by /motion/models)
// the two frame counts the pose-enhance model accepts, at its fixed 24fps
const ltxSeconds = (fullLength: boolean) => (fullLength ? 241 : 121) / 24;
// What a take IS, chosen before you author: the shot camera, the preview loop and
// the recorder all run on this one length, so the rehearsal is the take.
type TakeMode = "raw" | "ltx5" | "ltx10";
const TAKE_MODES: { id: TakeMode; label: string }[] = [
  { id: "raw", label: "10s raw" },
  { id: "ltx5", label: "LTX 5s" },
  { id: "ltx10", label: "LTX 10s" },
];
const modeSeconds = (mode: TakeMode) => (mode === "raw" ? TAKE_SECONDS : ltxSeconds(mode === "ltx10"));

// The ARDY rig faces +Z (its toe sits at +Z); a VRM after rotateVRM0 faces -Z.
const YAW_SKEL = 0;
const YAW_VRM = Math.PI;

// cskel27 joint name → VRM humanoid bone name, for retargeting ARDY motion onto a
// VRM skin. cskel27 has 4 spine joints vs the VRM's 3 (Spine2 is dropped) and no
// VRM slot for hand-end/thumb — those joints just don't drive the skin.
const VRM_BONE: Record<string, string> = {
  Hips: "hips", Spine: "spine", Spine1: "chest", Spine3: "upperChest", Neck: "neck", Head: "head",
  LeftShoulder: "leftShoulder", LeftArm: "leftUpperArm", LeftForeArm: "leftLowerArm", LeftHand: "leftHand",
  RightShoulder: "rightShoulder", RightArm: "rightUpperArm", RightForeArm: "rightLowerArm", RightHand: "rightHand",
  LeftUpLeg: "leftUpperLeg", LeftLeg: "leftLowerLeg", LeftFoot: "leftFoot", LeftToeBase: "leftToes",
  RightUpLeg: "rightUpperLeg", RightLeg: "rightLowerLeg", RightFoot: "rightFoot", RightToeBase: "rightToes",
};

type CamKey = { pos: THREE.Vector3; target: THREE.Vector3 };
type Take = { url: string; blob: Blob; duration: number; ltxReady: boolean; fullLength: boolean };
type Vec3 = [number, number, number];
type StageSave = {
  actors: { name: string; colorHex: number; spawn: Vec3; waypoints: [number, number][]; motion: Motion | null; prompt: string; vrmUrl: string | null }[];
  camA: { pos: Vec3; target: Vec3 } | null;
  camB: { pos: Vec3; target: Vec3 } | null;
  props: { name: string; url: string; matrix: number[] }[];
};
const STAGE_STORE_KEY = "pioneer_studio_stage";
type ActorInfo = { id: number; name: string; colorHex: number; waypoints: number; prompt: string; hasMotion: boolean; genSeconds: number | null };

const smoothstep = (x: number) => x * x * (3 - 2 * x);

class Actor {
  root = new THREE.Group();
  /** Where this actor's performance is planted; ARDY supplies motion from here. */
  spawn = new THREE.Vector3();
  waypoints: THREE.Vector3[] = [];
  motion: Motion | null = null;
  prompt = "";
  vrmUrl: string | null = null; // source url of the attached skin, for persistence (http only)
  rig: Rig;
  vrm: VRM | null = null;
  wpGroup = new THREE.Group();
  private line: THREE.Line | null = null;
  private lineMat = new THREE.LineBasicMaterial({ color: 0x7fae8f });
  private dotMat: THREE.MeshBasicMaterial;
  private static dotGeo = new THREE.CylinderGeometry(0.09, 0.09, 0.02, 20);

  id: number;
  name: string;
  colorHex: number;

  constructor(id: number, name: string, colorHex: number) {
    this.id = id;
    this.name = name;
    this.colorHex = colorHex;
    this.rig = buildRig(colorHex);
    this.root.add(this.rig.root);
    this.dotMat = new THREE.MeshBasicMaterial({ color: colorHex });
  }

  setVrm(vrm: VRM | null) {
    if (this.vrm) {
      this.root.remove(this.vrm.scene);
      VRMUtils.deepDispose(this.vrm.scene);
    }
    this.vrm = vrm;
    if (vrm) this.root.add(vrm.scene);
    this.rig.root.visible = !vrm; // the skeleton IS the deliverable; VRM is a preview skin
  }

  setAidsVisible(v: boolean) {
    this.wpGroup.visible = v;
    if (this.line) this.line.visible = v;
  }

  rebuildPathViz(scene: THREE.Scene) {
    this.wpGroup.clear();
    if (this.line) {
      scene.remove(this.line);
      this.line.geometry.dispose();
      this.line = null;
    }
    for (const p of this.waypoints) {
      const m = new THREE.Mesh(Actor.dotGeo, this.dotMat);
      m.position.set(p.x, 0.01, p.z);
      this.wpGroup.add(m);
    }
    if (this.waypoints.length > 1) {
      const g = new THREE.BufferGeometry().setFromPoints(this.waypoints.map((p) => new THREE.Vector3(p.x, 0.02, p.z)));
      this.line = new THREE.Line(g, this.lineMat);
      scene.add(this.line);
    }
  }

  /** Apply real ARDY motion at time t.
   *
   *  The service returns LOCAL joint quaternions on `cskel27` — the same rig
   *  `buildRig` builds — so frames drop straight onto the bones with no
   *  retargeting. Root motion comes from ARDY too; `spawn` only offsets where
   *  the performance happens on the stage.
   *
   *  Sampled by frame index rather than integrated per tick, so scrubbing is
   *  exact and a re-record reproduces the take frame for frame. */
  pose(t: number) {
    const m = this.motion;
    if (!m) return this.idlePose(t);

    const f = Math.max(0, Math.min(m.num_frames - 1, Math.round(t * m.fps)));
    const rp = m.data.root_positions[f];
    const quats = m.data.joint_rotations_quat[f];

    this.root.position.set(this.spawn.x, 0, this.spawn.z);
    this.root.rotation.y = this.vrm ? YAW_VRM : YAW_SKEL;
    // ARDY's root position is the hips in world space (y ≈ HIP_HEIGHT), and the
    // rig group already sits at HIP_HEIGHT — so drive the group from ARDY's root
    // directly rather than stacking the two.
    this.rig.root.position.set(rp[0], rp[1], rp[2]);
    for (let j = 0; j < JOINTS.length && j < quats.length; j++) {
      const q = quats[j];
      this.rig.bones.get(JOINTS[j].name)?.quaternion.set(q[0], q[1], q[2], q[3]);
    }
    // Retarget onto a VRM skin. cskel27 and the VRM humanoid are
    // both Mixamo-family T-poses, so the LOCAL joint quaternions transfer directly
    // to the matching normalized bone — no rest-pose delta needed. The hips bone
    // carries the root translation. The 180° root yaw (VRM faces -Z) keeps facing
    // and travel consistent.
    if (this.vrm?.humanoid) {
      const h = this.vrm.humanoid;
      for (let j = 0; j < JOINTS.length && j < quats.length; j++) {
        const vname = VRM_BONE[JOINTS[j].name];
        if (!vname) continue;
        const q = quats[j];
        h.getNormalizedBoneNode(vname as any)?.quaternion.set(q[0], q[1], q[2], q[3]);
      }
      const hips = h.getNormalizedBoneNode("hips");
      if (hips) hips.position.set(rp[0], rp[1], rp[2]);
    }
  }

  /** No motion yet: stand in a readable rest pose (T-pose arms dropped). */
  private idlePose(t: number) {
    this.root.position.set(this.spawn.x, 0, this.spawn.z);
    // same facing as pose(), else a VRM idles backwards then snaps 180° on generate
    this.root.rotation.y = this.vrm ? YAW_VRM : YAW_SKEL;
    this.rig.root.position.set(0, HIP_HEIGHT, 0);
    const h = this.vrm?.humanoid;
    const sway = Math.sin(t * 1.7) * 0.02;
    // The rigs' rest frames differ by a 180° yaw (VRM faces -Z, the ARDY rig +Z),
    // and conjugating by that yaw negates X and Z while leaving Y — so one sign
    // flip serves both. Without it the arms rise instead of dropping.
    const s = this.vrm ? 1 : -1;
    const get = (n: string) =>
      h ? h.getNormalizedBoneNode(n as Parameters<typeof h.getNormalizedBoneNode>[0]) : null;
    const bone = (vrmName: string, skelName: string) =>
      h ? get(vrmName) : this.rig.bones.get(skelName) ?? null;
    bone("leftUpperArm", "LeftArm")?.rotation.set(sway * s, 0, ARM_DOWN * s);
    bone("rightUpperArm", "RightArm")?.rotation.set(sway * s, 0, -ARM_DOWN * s);
  }

  dispose(scene: THREE.Scene) {
    this.rig.dispose();
    this.setVrm(null);
    if (this.line) scene.remove(this.line);
    this.dotMat.dispose();
    this.lineMat.dispose();
  }
}

class Stage {
  renderer: THREE.WebGLRenderer;
  scene = new THREE.Scene();
  authorCam: THREE.PerspectiveCamera;
  shotCam: THREE.PerspectiveCamera;
  controls: OrbitControls;
  actors: Actor[] = [];
  props: Prop[] = [];
  selectedProp: number | null = null;
  gizmo: TransformControls | null = null;
  selected = 0;
  camA: CamKey | null = null;
  camB: CamKey | null = null;
  t = 0;
  playing = false;
  camMode: "author" | "shot" = "author";
  recording = false;
  active = true;
  onTick: () => void = () => {};
  onRecorded: (b: Blob, meta: { duration: number; ltxReady: boolean; fullLength: boolean }) => void = () => {};
  private clock = new THREE.Clock();
  private raf = 0;
  private recorder: MediaRecorder | null = null;
  private recStartMs = 0;
  takeMode: TakeMode = "raw";
  get takeSeconds() {
    return modeSeconds(this.takeMode);
  }
  private recSeconds = TAKE_SECONDS;
  private recLtx = false;
  private recLtxFull = false;
  private recTimer = 0;
  private recStream: MediaStream | null = null;
  private ground: THREE.Mesh;
  private downAt: { x: number; y: number } | null = null;
  private nextId = 0;
  private nextPropId = 0;
  private ro: ResizeObserver | null = null;
  private _v = new THREE.Vector3();
  mount: HTMLDivElement;

  constructor(mount: HTMLDivElement) {
    this.mount = mount;
    this.renderer = new THREE.WebGLRenderer({ antialias: true });
    this.renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
    this.renderer.outputColorSpace = THREE.SRGBColorSpace;
    mount.appendChild(this.renderer.domElement);

    this.scene.background = new THREE.Color(0x0a1410);
    this.scene.fog = new THREE.Fog(0x0a1410, 16, 46);
    this.scene.add(new THREE.HemisphereLight(0xcfe8d8, 0x0c1a12, 1.2));
    const sun = new THREE.DirectionalLight(0xfff2d8, 1.5);
    sun.position.set(4, 8, 5);
    this.scene.add(sun, new THREE.GridHelper(40, 40, 0x2e5c44, 0x182e22));

    this.ground = new THREE.Mesh(new THREE.PlaneGeometry(200, 200), new THREE.MeshBasicMaterial({ visible: false }));
    this.ground.rotation.x = -Math.PI / 2;
    this.scene.add(this.ground);

    this.authorCam = new THREE.PerspectiveCamera(40, 1, 0.1, 200);
    this.authorCam.position.set(4.5, 2.4, 6);
    this.shotCam = this.authorCam.clone();
    this.controls = new OrbitControls(this.authorCam, this.renderer.domElement);
    this.controls.target.set(0, 1, 0);
    this.controls.maxPolarAngle = Math.PI / 2 - 0.02;

    this.renderer.domElement.addEventListener("pointerdown", (e) => (this.downAt = { x: e.clientX, y: e.clientY }));
    this.renderer.domElement.addEventListener("pointerup", (e) => {
      const d = this.downAt;
      this.downAt = null;
      if (!d || e.button !== 0 || Math.hypot(e.clientX - d.x, e.clientY - d.y) > 5) return;
      this.clickGround(e);
    });

    // Prop gizmo — real move/rotate/scale, and OrbitControls must yield while dragging
    const g = new TransformControls(this.authorCam, this.renderer.domElement);
    g.addEventListener("dragging-changed", (e) => (this.controls.enabled = !e.value));
    const helper = (g as any).getHelper?.() ?? (g as unknown as THREE.Object3D);
    this.scene.add(helper);
    g.enabled = false;
    (helper as THREE.Object3D).visible = false;
    this.gizmo = g;

    initPropLoader(this.renderer); // KTX2 needs a renderer to pick a transcode target

    this.ro = new ResizeObserver(() => this.resize());
    this.ro.observe(mount);
    this.resize();
    this.loop();
  }

  resize() {
    if (this.recording && this.recLtx) return;
    const w = this.mount.clientWidth || 1;
    const h = this.mount.clientHeight || 1;
    this.renderer.setSize(w, h);
    for (const c of [this.authorCam, this.shotCam]) {
      c.aspect = w / h;
      c.updateProjectionMatrix();
    }
  }

  addActor(): Actor {
    const i = this.nextId++;
    const c = ACTOR_COLORS[i % ACTOR_COLORS.length];
    const a = new Actor(i, `Actor ${i + 1}`, c.hex);
    // Spread spawns so a fresh actor isn't hidden inside the previous one.
    // This MUST write `spawn`, not root.position: pose()/idlePose() rebuild
    // root.position from spawn every frame, so anything written to root.position
    // is clobbered on the next tick.
    a.spawn.set(i * 0.9, 0, 0);
    this.actors.push(a);
    this.scene.add(a.root, a.wpGroup);
    this.selected = this.actors.length - 1;
    this.onTick();
    return a;
  }
  removeActor(id: number) {
    const i = this.actors.findIndex((a) => a.id === id);
    if (i < 0) return;
    const a = this.actors[i];
    this.scene.remove(a.root, a.wpGroup);
    a.dispose(this.scene);
    this.actors.splice(i, 1);
    this.selected = Math.max(0, Math.min(this.selected, this.actors.length - 1));
    this.onTick();
  }
  get current(): Actor | undefined {
    return this.actors[this.selected];
  }

  async loadVrm(url: string, actor?: Actor) {
    const a = actor ?? this.current;
    if (!a) return;
    const loader = makeGltfLoader(this.renderer);
    loader.register((p) => new VRMLoaderPlugin(p));
    const gltf = await loader.loadAsync(url);
    const vrm = gltf.userData.vrm as VRM;
    VRMUtils.rotateVRM0(vrm);
    vrm.scene.traverse((o) => (o.frustumCulled = false));
    a.setVrm(vrm);
    a.vrmUrl = /^https?:\/\//.test(url) ? url : null; // blob: urls can't be restored
    this.onTick();
  }

  clickGround(e: PointerEvent) {
    const a = this.current;
    if (!a || this.gizmo?.dragging) return;
    const r = this.renderer.domElement.getBoundingClientRect();
    const ray = new THREE.Raycaster();
    // pick through whichever camera is on screen, else clicks land somewhere else
    const cam = this.camMode === "shot" ? this.shotCam : this.authorCam;
    ray.setFromCamera(new THREE.Vector2(((e.clientX - r.left) / r.width) * 2 - 1, -((e.clientY - r.top) / r.height) * 2 + 1), cam);
    const hit = ray.intersectObject(this.ground)[0];
    if (!hit) return;
    a.waypoints.push(new THREE.Vector3(hit.point.x, 0, hit.point.z));
    a.rebuildPathViz(this.scene);
    this.onTick();
  }
  clearWaypoints() {
    const a = this.current;
    if (!a) return;
    a.waypoints = [];
    a.rebuildPathViz(this.scene);
    this.onTick();
  }

  /* ── props ── */
  async addProp(name: string, url: string): Promise<Prop> {
    const p = await loadProp(this.nextPropId++, name, url);
    this.props.push(p);
    this.scene.add(p.root);
    this.selectProp(p.id);
    this.onTick();
    return p;
  }
  removeProp(id: number) {
    const i = this.props.findIndex((p) => p.id === id);
    if (i < 0) return;
    if (this.selectedProp === id) this.selectProp(null);
    this.scene.remove(this.props[i].root);
    this.props[i].dispose();
    this.props.splice(i, 1);
    this.onTick();
  }
  selectProp(id: number | null) {
    this.selectedProp = id;
    const p = id === null ? null : this.props.find((x) => x.id === id);
    const helper = (this.gizmo as any)?.getHelper?.() ?? (this.gizmo as unknown as THREE.Object3D);
    if (!this.gizmo) return;
    if (p) {
      this.gizmo.attach(p.root);
      this.gizmo.enabled = true;
      // never un-hide mid-take: the gizmo would land in the control video
      if (helper) (helper as THREE.Object3D).visible = !this.recording;
    } else {
      this.gizmo.detach();
      this.gizmo.enabled = false;
      if (helper) (helper as THREE.Object3D).visible = false;
    }
    this.onTick();
  }
  /** Authoring aids (waypoint discs + path lines) must not be baked into a take. */
  private setAidsVisible(v: boolean) {
    for (const a of this.actors) a.setAidsVisible(v);
  }

  setGizmoMode(m: "translate" | "rotate" | "scale") {
    this.gizmo?.setMode(m);
    this.onTick();
  }

  /** Generate real motion for an actor. Waypoints ride along as an ARDY `root2d`
   *  kinematic constraint when present. */
  async generateFor(a: Actor, apiKey: string, prompt: string): Promise<Motion> {
    const constraints: MotionConstraint[] | undefined =
      a.waypoints.length >= 2
        ? [
            {
              type: "root2d",
              // spread the waypoints evenly across the take
              // 20 = the `core` checkpoint's fps (the only model we request). A
              // different model (g1 is 25fps) would need its fps from /motion/models.
              frame_indices: a.waypoints.map((_, i) =>
                Math.round((i / (a.waypoints.length - 1)) * (TAKE_SECONDS * CORE_FPS - 1)),
              ),
              root_2d: a.waypoints.map((w) => [w.x - a.spawn.x, w.z - a.spawn.z] as [number, number]),
            },
          ]
        : undefined;
    const m = await generateMotion(apiKey, { prompt, duration_s: TAKE_SECONDS, model: "core", constraints });
    a.motion = m;
    a.prompt = prompt;
    this.t = 0;
    this.onTick();
    return m;
  }

  keyFromView(): CamKey {
    return { pos: this.authorCam.position.clone(), target: this.controls.target.clone() };
  }
  private applyShotCam() {
    const a = this.camA ?? this.keyFromView();
    const b = this.camB ?? a;
    // over the take's own length, not a fixed 10s: a 5s take must still travel
    // the whole authored A→B move, not stop halfway.
    const k = smoothstep(Math.max(0, Math.min(1, this.t / this.takeSeconds)));
    this.shotCam.position.lerpVectors(a.pos, b.pos, k);
    this._v.lerpVectors(a.target, b.target, k);
    this.shotCam.lookAt(this._v);
  }

  record(mode: TakeMode = this.takeMode) {
    if (this.recording) return;
    this.takeMode = mode;
    const ltxReady = mode !== "raw";
    this.recLtx = ltxReady;
    this.recLtxFull = mode === "ltx10";
    this.recSeconds = this.takeSeconds;
    if (ltxReady) {
      // The enhancement model expects a 768×448, 24fps control input.
      // MediaRecorder may emit a frame or two either side of the 121/241 target.
      this.renderer.setPixelRatio(1);
      this.renderer.setSize(768, 448, false);
      for (const camera of [this.authorCam, this.shotCam]) {
        camera.aspect = 768 / 448;
        camera.updateProjectionMatrix();
      }
    }
    const mime = ["video/webm;codecs=vp9", "video/webm;codecs=vp8", "video/webm", "video/mp4"].find((m) => MediaRecorder.isTypeSupported(m));
    this.recStream = this.renderer.domElement.captureStream(ltxReady ? 24 : 30);
    const rec = new MediaRecorder(this.recStream, { mimeType: mime, videoBitsPerSecond: 8_000_000 });
    const chunks: Blob[] = [];
    rec.ondataavailable = (e) => e.data.size && chunks.push(e.data);
    rec.onstop = () =>
      this.onRecorded(new Blob(chunks, { type: mime || "video/webm" }), {
        duration: this.recSeconds,
        ltxReady: this.recLtx,
        fullLength: this.recLtxFull,
      });
    // Nothing that is an authoring aid may appear in a control video the AI pass
    // conditions on — gizmo and waypoint markers/paths alike.
    const helper = (this.gizmo as any)?.getHelper?.() ?? (this.gizmo as unknown as THREE.Object3D);
    if (helper) (helper as THREE.Object3D).visible = false;
    this.setAidsVisible(false);
    this.recorder = rec;
    this.t = 0;
    this.camMode = "shot";
    this.playing = true;
    this.recording = true;
    this.recStartMs = performance.now();
    // MediaRecorder runs on wall clock, so the take MUST end on wall clock too.
    // Relying on the rAF loop to notice t >= TAKE_SECONDS deadlocks the moment
    // rAF stalls (background the tab mid-take): t freezes, the loop's `!active`
    // guard skips the check, the recorder runs forever and every control stays
    // disabled behind `recording`. This timer is the guarantee.
    clearTimeout(this.recTimer);
    this.recTimer = window.setTimeout(() => this.stopRecording(), this.recSeconds * 1000 + 200);
    rec.start();
  }
  private stopRecording() {
    if (!this.recording) return;
    clearTimeout(this.recTimer);
    this.recTimer = 0;
    this.recording = false;
    this.playing = false;
    this.t = this.recSeconds;
    this.camMode = "author";
    for (const tr of this.recStream?.getTracks() ?? []) tr.stop();
    this.recStream = null;
    this.onTick(); // the loop won't tick again once recording+playing are false
    const helper = (this.gizmo as any)?.getHelper?.() ?? (this.gizmo as unknown as THREE.Object3D);
    if (helper && this.selectedProp !== null) (helper as THREE.Object3D).visible = true;
    this.setAidsVisible(true);
    this.recorder?.stop();
    this.recorder = null;
    if (this.recLtx) {
      this.renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
      this.resize();
    }
  }

  private loop = () => {
    this.raf = requestAnimationFrame(this.loop);
    const dt = Math.min(this.clock.getDelta(), 0.1);
    // a take in progress must keep drawing even when the user leaves the tab —
    // captureStream only sees frames we actually render
    if (!this.active && !this.recording) return;
    if (this.recording) {
      // Wall clock, not integrated dt: dt is clamped to 0.1 so a slow frame makes
      // t lag real time, which would stretch a 10s take into a slow-motion video
      // that ends early. Sampling by elapsed time keeps the take honest.
      this.t = Math.min(this.recSeconds, (performance.now() - this.recStartMs) / 1000);
      if (this.t >= this.recSeconds) this.stopRecording();
      this.onTick();
    } else if (this.playing) {
      this.t += dt;
      if (this.t >= this.takeSeconds) this.t = 0;
      this.onTick();
    }
    for (const a of this.actors) {
      a.pose(this.t);
      a.vrm?.update(dt);
    }
    this.controls.update();
    if (this.camMode === "shot") this.applyShotCam();
    this.renderer.render(this.scene, this.camMode === "shot" ? this.shotCam : this.authorCam);
  };

  /* ── persistence ── */
  // A staged scene is JSON: actor rigs + baked motion + paths + skins, camera
  // keys, and props (only those with a stable http url — blob: uploads can't be
  // restored). Object-URL skins/props are dropped on save; everything else
  // round-trips so a half-staged scene survives a reload.
  serialize(): StageSave {
    const v3 = (v: THREE.Vector3): [number, number, number] => [v.x, v.y, v.z];
    return {
      actors: this.actors.map((a) => ({
        name: a.name,
        colorHex: a.colorHex,
        spawn: v3(a.spawn),
        waypoints: a.waypoints.map((w) => [w.x, w.z] as [number, number]),
        motion: a.motion,
        prompt: a.prompt,
        vrmUrl: a.vrmUrl,
      })),
      camA: this.camA ? { pos: v3(this.camA.pos), target: v3(this.camA.target) } : null,
      camB: this.camB ? { pos: v3(this.camB.pos), target: v3(this.camB.target) } : null,
      props: this.props.filter((p) => p.url).map((p) => ({ name: p.name, url: p.url, matrix: p.root.matrix.toArray() })),
    };
  }

  restore(s: StageSave) {
    for (const a of this.actors.slice()) this.removeActor(a.id);
    for (const p of this.props.slice()) this.removeProp(p.id);
    this.nextId = 0;
    for (const sa of s.actors ?? []) {
      const a = new Actor(this.nextId, sa.name, sa.colorHex);
      this.nextId++;
      a.spawn.set(sa.spawn[0], sa.spawn[1], sa.spawn[2]);
      a.waypoints = (sa.waypoints ?? []).map(([x, z]) => new THREE.Vector3(x, 0, z));
      a.motion = sa.motion ?? null;
      a.prompt = sa.prompt ?? "";
      this.actors.push(a);
      this.scene.add(a.root, a.wpGroup);
      a.rebuildPathViz(this.scene);
      if (sa.vrmUrl) this.loadVrm(sa.vrmUrl, a).catch(() => {});
    }
    this.selected = 0;
    this.camA = s.camA ? { pos: new THREE.Vector3(...s.camA.pos), target: new THREE.Vector3(...s.camA.target) } : null;
    this.camB = s.camB ? { pos: new THREE.Vector3(...s.camB.pos), target: new THREE.Vector3(...s.camB.target) } : null;
    for (const sp of s.props ?? [])
      this.addProp(sp.name, sp.url)
        .then((p) => {
          p.root.matrix.fromArray(sp.matrix);
          p.root.matrix.decompose(p.root.position, p.root.quaternion, p.root.scale);
        })
        .catch(() => {});
    this.selectProp(null);
    this.onTick();
  }

  dispose() {
    cancelAnimationFrame(this.raf);
    clearTimeout(this.recTimer);
    this.ro?.disconnect();
    this.controls.dispose();
    for (const tr of this.recStream?.getTracks() ?? []) tr.stop();
    this.recorder?.stop();
    for (const a of this.actors) a.dispose(this.scene);
    for (const p of this.props) p.dispose();
    this.gizmo?.dispose();
    this.renderer.dispose();
    this.mount.removeChild(this.renderer.domElement);
  }
}

export default function StageView({ ps, active }: { ps: PS; active: boolean }) {
  const mountRef = useRef<HTMLDivElement>(null);
  const stageRef = useRef<Stage | null>(null);
  const [t, setT] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [recording, setRecording] = useState(false);
  const [camMode, setCamMode] = useState<"author" | "shot">("author");
  const [keys, setKeys] = useState({ a: false, b: false });
  const [actors, setActors] = useState<ActorInfo[]>([]);
  const [selected, setSelected] = useState(0);
  const [props, setProps] = useState<PropInfo[]>([]);
  const [selectedProp, setSelectedProp] = useState<number | null>(null);
  const [gizmoMode, setGizmoMode] = useState<"translate" | "rotate" | "scale">("translate");
  const [prompt, setPrompt] = useState("");
  const [generating, setGenerating] = useState(false);
  const [motionUp, setMotionUp] = useState<boolean | null>(null);
  const [take, setTake] = useState<Take | null>(null);
  const [saving, setSaving] = useState(false);
  const [uploadedTake, setUploadedTake] = useState<UploadResponse | null>(null);
  const [enhancePrompt, setEnhancePrompt] = useState("");
  const [referenceSheet, setReferenceSheet] = useState("");
  // blank = let the model roll its own; a pinned seed is what keeps a series on model
  const [seed, setSeed] = useState("");
  // 1 = the skeleton is law; lower it to trade pose fidelity for the model's own motion sense
  const [guideStrength, setGuideStrength] = useState(1);
  const [takeMode, setTakeMode] = useState<TakeMode>("raw");
  const takeSeconds = modeSeconds(takeMode);
  const [enhancing, setEnhancing] = useState(false);
  // what the render is actually doing — a long job and a hung one look identical
  // from a spinner alone
  const [jobNote, setJobNote] = useState("");
  const [finishedTake, setFinishedTake] = useState<Artifact | null>(null);
  const uploadedTakeRef = useRef<UploadResponse | null>(null);
  const promptRef = useRef(prompt);
  promptRef.current = prompt;
  const psRef = useRef(ps);
  psRef.current = ps;

  useEffect(() => {
    const stage = new Stage(mountRef.current!);
    stageRef.current = stage;
    stage.onTick = () => {
      setT(stage.t);
      setPlaying(stage.playing);
      setRecording(stage.recording);
      setCamMode(stage.camMode);
      setTakeMode(stage.takeMode);
      setSelected(stage.selected);
      setActors(stage.actors.map((a) => ({ id: a.id, name: a.name, colorHex: a.colorHex, waypoints: a.waypoints.length,
        prompt: a.prompt, hasMotion: !!a.motion, genSeconds: a.motion?.generation_seconds ?? null })));
      setProps(stage.props.map((p) => ({ id: p.id, name: p.name, visible: p.root.visible })));
      setSelectedProp(stage.selectedProp);
    };
    stage.onRecorded = (blob, meta) => {
      setTake((old) => {
        if (old) URL.revokeObjectURL(old.url);
        return { url: URL.createObjectURL(blob), blob, ...meta };
      });
      uploadedTakeRef.current = null;
      setUploadedTake(null);
      setFinishedTake(null);
      psRef.current.toast("Take recorded", "ok");
    };
    // restore a saved scene, else start with one actor
    let restored = false;
    try {
      const raw = localStorage.getItem(STAGE_STORE_KEY);
      if (raw) {
        const save = JSON.parse(raw) as StageSave;
        if (save?.actors?.length) {
          stage.restore(save);
          restored = true;
        }
      }
    } catch {
      /* corrupt save → fresh */
    }
    if (!restored) stage.addActor();
    // debounced autosave — onTick fires every frame while playing, so coalesce
    let saveTimer = 0;
    const baseTick = stage.onTick;
    stage.onTick = () => {
      baseTick();
      if (stage.recording) return; // motion doesn't change during a take
      clearTimeout(saveTimer);
      saveTimer = window.setTimeout(() => {
        try {
          localStorage.setItem(STAGE_STORE_KEY, JSON.stringify(stage.serialize()));
        } catch {
          // over quota (baked motion is big) → save without motion rather than lose the scene
          try {
            const lean = stage.serialize();
            lean.actors.forEach((a) => (a.motion = null));
            localStorage.setItem(STAGE_STORE_KEY, JSON.stringify(lean));
          } catch {
            /* give up silently */
          }
        }
      }, 1200);
    };
    psRef.current.registerSuggestions("animate", [
      { label: "Add an actor", run: () => stageRef.current?.addActor() },
      { label: "Record a 10s take", run: () => stageRef.current?.record("raw") },
      { label: "Record a 5s LTX control take", run: () => stageRef.current?.record("ltx5") },
      { label: "Record a 10s LTX control take", run: () => stageRef.current?.record("ltx10") },
    ]);
    // Detect whether the ARDY motion service is reachable, so the UI can say so
    // plainly instead of failing at the first Generate.
    const key = psRef.current.apiKey;
    if (key) fetchMotionModels(key).then((m) => setMotionUp(m.length > 0)).catch(() => setMotionUp(false));
    else setMotionUp(null);
    return () => stage.dispose();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const stage = stageRef.current;
    if (!stage) return;
    stage.active = active;
    // Create→Animation handoff: a character sent its VRM here → spawn an actor
    // wearing it. Consumed once (cleared), so it doesn't re-fire on every switch.
    if (active) {
      const pending = consumeCharacter("animate");
      if (pending?.vrmUrl) {
        const a = stage.addActor();
        if (pending.name) a.name = pending.name;
        stage
          .loadVrm(pending.vrmUrl, a)
          .then(() => psRef.current.toast(`${pending!.name || "Character"} added as an actor`, "gold"))
          .catch((e) => psRef.current.toast(`Skin load failed: ${e.message || e}`));
      }
    }
  }, [active]);

  const stage = () => stageRef.current!;
  const hex = (n: number) => "#" + n.toString(16).padStart(6, "0");

  async function generate() {
    const a = stage().current;
    if (!a) return;
    const text = promptRef.current.trim();
    if (!text) return ps.toast("Describe the motion first");
    if (!ps.apiKey) return ps.toast("Add your key in Settings to generate motion");
    setGenerating(true);
    ps.setAiState("generating motion", true);
    try {
      const m = await stage().generateFor(a, ps.apiKey, text);
      ps.toast(`${a.name}: ${m.num_frames}f @ ${m.fps}fps in ${m.generation_seconds.toFixed(2)}s`, "gold");
      setMotionUp(true);
    } catch (e: any) {
      const msg = String(e.message || e);
      // Waypoints ride as an ARDY root2d constraint; that path 500s upstream
      // today, so fall back to the unconstrained prompt rather than dead-ending.
      if (a.waypoints.length >= 2 && /50\d/.test(msg)) {
        const saved = a.waypoints;
        try {
          a.waypoints = [];
          const m = await stage().generateFor(a, ps.apiKey, text);
          ps.toast(`Waypoint constraints unavailable upstream — generated from the prompt alone (${m.generation_seconds.toFixed(2)}s)`);
          setMotionUp(true);
          return;
        } catch {
          /* fall through to the original error */
        } finally {
          // must be a finally: if the retry throws, the catch below swallows it and
          // the user's clicked path would be gone for good while its discs still render
          a.waypoints = saved;
          stage().onTick();
        }
      }
      ps.toast(msg.slice(0, 140));
    } finally {
      setGenerating(false);
      ps.setAiState("idle", false);
    }
  }

  async function importProp(f: File | undefined) {
    if (!f) return;
    if (!isPropFile(f.name)) return ps.toast("Props must be .glb or .gltf");
    const url = URL.createObjectURL(f);
    try {
      await stage().addProp(f.name.replace(/\.(glb|gltf)$/i, ""), url);
      ps.toast(`Prop “${f.name}” imported`, "ok");
    } catch (e: any) {
      ps.toast(`Prop failed: ${String(e.message || e).slice(0, 90)}`);
    } finally {
      URL.revokeObjectURL(url);
    }
  }

  function loadFile(f: File | undefined) {
    if (!f || !/\.vrm$/i.test(f.name)) return;
    const url = URL.createObjectURL(f);
    stage()
      .loadVrm(url)
      .then(() => ps.toast(`${f.name} → ${stage().current?.name}`, "ok"))
      .catch((e) => ps.toast(`VRM load failed: ${e.message || e}`))
      .finally(() => URL.revokeObjectURL(url)); // else every dropped file is pinned for the session
  }

  async function uploadCurrentTake(): Promise<UploadResponse> {
    if (!take) throw new Error("record an ARDY take first");
    if (uploadedTakeRef.current) return uploadedTakeRef.current;
    const ext = take.blob.type.includes("mp4") ? "mp4" : "webm";
    const name = `raw-take-${Date.now()}.${ext}`;
    const uploaded = await uploadMedia(ps.apiKey, new File([take.blob], name, { type: take.blob.type }));
    uploadedTakeRef.current = uploaded;
    setUploadedTake(uploaded);
    ps.refreshMedia();
    return uploaded;
  }

  function queueTake(uploaded: UploadResponse, name = `raw-take.${take?.blob.type.includes("mp4") ? "mp4" : "webm"}`) {
    queueStudioAsset({
      projectId: ps.board?.id || "default",
      sourceId: `take:${uploaded.key}`,
      name,
      url: uploaded.url,
      contentType: uploaded.content_type,
      kind: "video",
      duration: take?.duration ?? TAKE_SECONDS,
    });
  }

  function applyTakeMode(mode: TakeMode) {
    const s = stage();
    s.takeMode = mode;
    s.t = Math.min(s.t, s.takeSeconds); // a shorter take can't sit past its own end
    s.onTick();
  }

  async function saveToMedia() {
    if (!take) return;
    if (!ps.apiKey) return ps.toast("Add your key in Settings to save takes");
    setSaving(true);
    try {
      const uploaded = await uploadCurrentTake();
      queueTake(uploaded);
      ps.toast("Raw take saved and queued on the Studio timeline", "gold");
    } catch (e: any) {
      ps.toast(`Save failed (${e.message || e}) — use Download instead`);
    } finally {
      setSaving(false);
    }
  }

  async function enhanceTake() {
    if (!take) return ps.toast("Record an ARDY take first");
    if (!take.ltxReady) return ps.toast("Record in LTX 5s or LTX 10s mode before running pose-controlled enhancement");
    if (!ps.apiKey) return ps.toast("Add your key in Settings to finish the take");
    if (!pickModel(ps.models, "motion_video")) return ps.toast("Pose-controlled enhancement is not available through the Pioneer API");
    const fallbackPrompt = stage().actors
      .map((actor) => `${actor.name}: ${actor.prompt || "performs the authored motion"}`)
      .join(". ");
    const visualPrompt = enhancePrompt.trim() || `${fallbackPrompt}. cinematic live-action finish, coherent character identity, detailed environment`;
    setEnhancing(true);
    setJobNote("uploading the control take…");
    ps.setAiState("finishing ARDY take with LTX", true);
    const startedAt = Date.now();
    try {
      const uploaded = await uploadCurrentTake();
      setJobNote("submitting…");
      const result = await enhanceMotionVideo(ps, visualPrompt, uploaded.url, {
        referenceSheet: referenceSheet || undefined,
        fullLength: take.fullLength,
        guideStrength,
        seed: seed.trim() && Number.isFinite(Number(seed)) ? Number(seed) : undefined,
        onPoll: (s) => {
          const elapsed = Math.round((Date.now() - startedAt) / 1000);
          const note = [s.status, s.stage, s.log_tail?.at(-1)].filter(Boolean).join(" · ");
          // full job id, not a prefix: it is the only handle for asking the API
          // what happened to a job that never came back
          setJobNote(`${note} · ${elapsed}s · job ${s.job_id}`);
          ps.setAiState(`LTX ${s.stage || s.status} ${elapsed}s`, true);
        },
      });
      const duration = ltxSeconds(take.fullLength);
      queueStudioAsset({
        projectId: ps.board?.id || "default",
        sourceId: `ltx-ardy:${result.url}`,
        name: `ltx-ardy-${Date.now()}.mp4`,
        url: result.url,
        contentType: result.content_type || "video/mp4",
        kind: "video",
        duration,
      });
      setFinishedTake(result);
      setJobNote(`done in ${Math.round((Date.now() - startedAt) / 1000)}s`);
      ps.refreshMedia();
      ps.toast(`LTX finished ${duration.toFixed(1)}s of authored ARDY motion and queued it in Studio`, "gold");
    } catch (e: any) {
      // toasts expire; a failed paid job's reason has to stay on screen
      setJobNote(`failed after ${Math.round((Date.now() - startedAt) / 1000)}s: ${String(e.message || e)}`);
      ps.toast(`LTX finish failed: ${String(e.message || e).slice(0, 140)}`);
    } finally {
      setEnhancing(false);
      ps.setAiState("idle", false);
    }
  }

  const actionFnsRef = useRef({ generate, saveToMedia, enhanceTake, applyTakeMode });
  actionFnsRef.current = { generate, saveToMedia, enhanceTake, applyTakeMode };
  useEffect(() => {
    registerActions([
      {
        name: "animate.get_state",
        description: "Animation-stage snapshot: time, playback, camera, actors, selection, prompt, recording, and take readiness",
        run: () => ({
          time: stageRef.current?.t || 0,
          playing: !!stageRef.current?.playing,
          camera: stageRef.current?.camMode,
          actors: stageRef.current?.actors.map((actor, index) => ({
            id: actor.id,
            index,
            name: actor.name,
            prompt: actor.prompt,
            waypoints: actor.waypoints.length,
            hasMotion: !!actor.motion,
            hasVrm: !!actor.vrm,
          })) || [],
          selectedActor: stageRef.current?.selected ?? null,
          prompt: promptRef.current,
          recording: !!stageRef.current?.recording,
          hasTake: !!take,
          takeMode: stageRef.current?.takeMode,
          takeSeconds: stageRef.current?.takeSeconds,
          ltxReadyTake: !!take?.ltxReady,
          ltxTakeSeconds: take?.ltxReady ? ltxSeconds(take.fullLength) : null,
          takeUploaded: !!uploadedTake,
          poseVideoModel: pickModel(psRef.current.models, "motion_video")?.model || null,
          hasFinishedTake: !!finishedTake,
        }),
      },
      {
        name: "animate.add_actor",
        description: "Add and select an actor, optionally naming it",
        parameters: { type: "object", properties: { name: { type: "string" } }, additionalProperties: false },
        run: (params) => {
          const actor = stageRef.current?.addActor();
          if (!actor) throw new Error("animation stage is not ready");
          if (params?.name) actor.name = String(params.name);
          stageRef.current?.onTick();
          return { id: actor.id, name: actor.name };
        },
      },
      {
        name: "animate.set_prompt",
        description: "Set the selected actor's motion prompt",
        parameters: { type: "object", properties: { prompt: { type: "string" } }, required: ["prompt"], additionalProperties: false },
        run: (params) => {
          const value = String(params?.prompt || "");
          promptRef.current = value;
          setPrompt(value);
          if (stageRef.current?.current) stageRef.current.current.prompt = value;
        },
      },
      {
        name: "animate.generate_motion",
        description: "Generate motion for the selected actor from its current prompt",
        confirmation: "Starts a paid motion-generation job",
        run: () => actionFnsRef.current.generate(),
      },
      {
        name: "animate.set_take_mode",
        description: "Set the take length the preview and recorder both run on: raw (10s), ltx5 or ltx10 (768×448, 24fps control take)",
        parameters: { type: "object", properties: { mode: { type: "string", enum: ["raw", "ltx5", "ltx10"] } }, required: ["mode"], additionalProperties: false },
        run: (params) => actionFnsRef.current.applyTakeMode(params?.mode as TakeMode),
      },
      {
        name: "animate.record_take",
        description: "Record the staged shot to a local take, optionally switching take mode first",
        parameters: { type: "object", properties: { mode: { type: "string", enum: ["raw", "ltx5", "ltx10"] } }, additionalProperties: false },
        run: (params) => stageRef.current?.record(params?.mode as TakeMode | undefined),
      },
      {
        name: "animate.save_take",
        description: "Upload the current raw take to Project Media",
        confirmation: "Uploads and stores the current take in Project Media",
        run: () => {
          if (!take?.ltxReady) throw new Error("record an LTX control take first");
          return actionFnsRef.current.saveToMedia();
        },
      },
      {
        name: "animate.enhance_take",
        description: "Finish the recorded ARDY skeleton take as a pose-controlled LTX video and queue it in Studio",
        confirmation: "Starts a paid LTX pose-controlled video job (1000cr for 5s or 2000cr for 10s)",
        run: () => {
          if (!take) throw new Error("record a take first");
          return actionFnsRef.current.enhanceTake();
        },
      },
    ]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [take, uploadedTake, finishedTake]);

  const cur = actors[selected];
  const motionVideoModel = pickModel(ps.models, "motion_video");
  const referenceImages = (ps.media?.objects || []).filter((object) => object.content_type.startsWith("image/"));

  return (
    <div
      className="stage-root"
      onDragOver={(e) => e.preventDefault()}
      onDrop={(e) => {
        e.preventDefault();
        const f = e.dataTransfer.files[0];
        if (!f) return;
        if (isPropFile(f.name)) importProp(f);
        else loadFile(f);
      }}
    >
      <div className="stage-canvas" ref={mountRef} />
      {takeMode !== "raw" && !recording && <div className="ltx-frame" />}

      <div className="stage-hud">
        <div className="stage-panel col">
          <div className="sp-head">
            <span className="sp-label">Cast</span>
            <button type="button" className="sp-btn" onClick={() => stage().addActor()}>
              + Actor
            </button>
          </div>
          <div className="actor-list">
            {actors.map((a, i) => (
              <div
                key={a.id}
                className={`actor-chip${i === selected ? " on" : ""}`}
                onClick={() => {
                  stage().selected = i;
                  setSelected(i);
                  setPrompt(a.prompt);
                }}
              >
                <span className="swatch" style={{ background: hex(a.colorHex) }} />
                <span className="an">{a.name}</span>
                <span className="sp-info">{a.waypoints ? `${a.waypoints} wp` : "no path"}</span>
                {actors.length > 1 && (
                  <button
                    type="button"
                    className="x"
                    title="Remove actor"
                    onClick={(e) => {
                      e.stopPropagation();
                      stage().removeActor(a.id);
                    }}
                  >
                    ✕
                  </button>
                )}
              </div>
            ))}
          </div>
          <div className="sp-info hint">Click the ground to path {cur?.name || "the actor"}</div>
        </div>

        {/* ── text → motion (real ARDY) ── */}
        <div className="stage-panel col">
          <div className="sp-head">
            <span className="sp-label">Motion</span>
            <span className="sp-info">
              {motionUp === false ? "service unreachable" : cur?.hasMotion ? `${cur.genSeconds?.toFixed(2)}s · ARDY` : "text → motion"}
            </span>
          </div>
          <textarea
            className="sp-prompt"
            rows={2}
            placeholder={`Describe what ${cur?.name || "the actor"} does…`}
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) generate();
            }}
          />
          <div className="sp-head">
            <button type="button" className="sp-btn gen" disabled={generating} onClick={generate}>
              {generating ? "Generating…" : "Generate motion"}
            </button>
            <button type="button" className="sp-btn" disabled={!cur?.waypoints} onClick={() => stage().clearWaypoints()}>
              Clear path
            </button>
          </div>
          {motionUp === false && (
            <div className="sp-info hint warn">
              ARDY motion is currently unavailable through the Pioneer API.
            </div>
          )}
        </div>

        {/* ── props ── */}
        <div className="stage-panel col">
          <div className="sp-head">
            <span className="sp-label">Props</span>
            <label className="sp-btn">
              + Import
              <input type="file" accept=".glb,.gltf" hidden onChange={(e) => importProp(e.target.files?.[0])} />
            </label>
          </div>
          {props.length > 0 && (
            <>
              <div className="actor-list">
                {props.map((p) => (
                  <div
                    key={p.id}
                    className={`actor-chip${selectedProp === p.id ? " on" : ""}`}
                    onClick={() => stage().selectProp(selectedProp === p.id ? null : p.id)}
                  >
                    <span className="swatch prop" />
                    <span className="an">{p.name}</span>
                    <button
                      type="button"
                      className="x"
                      title="Remove prop"
                      onClick={(e) => {
                        e.stopPropagation();
                        stage().removeProp(p.id);
                      }}
                    >
                      ✕
                    </button>
                  </div>
                ))}
              </div>
              {selectedProp !== null && (
                <div className="sp-head">
                  {(["translate", "rotate", "scale"] as const).map((m) => (
                    <button
                      key={m}
                      type="button"
                      className={`sp-btn${gizmoMode === m ? " on" : ""}`}
                      onClick={() => {
                        stage().setGizmoMode(m);
                        setGizmoMode(m);
                      }}
                    >
                      {m === "translate" ? "Move" : m === "rotate" ? "Rotate" : "Scale"}
                    </button>
                  ))}
                </div>
              )}
            </>
          )}
          <div className="sp-info hint">Drop a .glb/.gltf anywhere — tree, throne, anything</div>
        </div>

        <div className="stage-panel">
          <span className="sp-label">Skin</span>
          <VrmPicker
            ps={ps}
            className="sp-btn"
            label="Media VRM"
            disabled={!cur}
            onPick={(object) => stage().loadVrm(object.url).then(() => ps.toast(`${object.name} → ${stage().current?.name}`, "ok"))}
          />
          <label className="sp-btn" title="Attach a VRM to the selected actor (preview only — the skeleton performs)">
            Local VRM
            <input type="file" accept=".vrm" hidden onChange={(e) => loadFile(e.target.files?.[0])} />
          </label>
        </div>

        <div className="stage-panel">
          <span className="sp-label">Camera</span>
          <button
            type="button"
            className={`sp-btn${keys.a ? " on" : ""}`}
            title="Keyframe the shot camera at 0s from the current view"
            onClick={() => {
              stage().camA = stage().keyFromView();
              setKeys((k) => ({ ...k, a: true }));
            }}
          >
            Set start
          </button>
          <button
            type="button"
            className={`sp-btn${keys.b ? " on" : ""}`}
            title="Keyframe the shot camera at 10s from the current view"
            onClick={() => {
              stage().camB = stage().keyFromView();
              setKeys((k) => ({ ...k, b: true }));
            }}
          >
            Set end
          </button>
          <button
            type="button"
            className={`sp-btn${camMode === "shot" ? " on" : ""}`}
            onClick={() => {
              stage().camMode = camMode === "shot" ? "author" : "shot";
              setCamMode(stage().camMode);
            }}
          >
            Shot cam
          </button>
        </div>
      </div>

      <div className="stage-transport">
        <button
          type="button"
          className="sp-btn"
          disabled={recording}
          onClick={() => {
            stage().playing = !stage().playing;
            setPlaying(stage().playing);
          }}
        >
          {playing ? "⏸" : "▶"}
        </button>
        <input
          type="range"
          min={0}
          max={takeSeconds}
          step={0.01}
          value={t}
          disabled={recording}
          onChange={(e) => {
            stage().t = Number(e.target.value);
            setT(stage().t);
          }}
        />
        <span className="sp-info">
          {t.toFixed(1)}s / {takeSeconds.toFixed(takeMode === "raw" ? 0 : 2)}s
        </span>
        {TAKE_MODES.map((m) => (
          <button
            key={m.id}
            type="button"
            className={`sp-btn${takeMode === m.id ? " on" : ""}`}
            disabled={recording}
            onClick={() => applyTakeMode(m.id)}
          >
            {m.label}
          </button>
        ))}
        <button type="button" className={`sp-btn rec${recording ? " on" : ""}`} disabled={recording} onClick={() => stage().record()}>
          {recording ? "Recording…" : "● Record take"}
        </button>
      </div>

      {take && (
        <div className="stage-take">
          <div className="st-title">
            <span className="sp-label">ARDY control take</span>
            <span className="sp-info">{take.ltxReady ? `LTX ${take.fullLength ? "10s" : "5s"}` : `${take.duration.toFixed(0)}s raw`} · {uploadedTake ? "uploaded" : "local"}</span>
          </div>
          <video src={take.url} controls autoPlay loop muted />
          <div className="st-row">
            <a className="sp-btn" href={take.url} download={`raw-take.${take.blob.type.includes("mp4") ? "mp4" : "webm"}`}>
              Download
            </a>
            <button type="button" className="sp-btn" disabled={saving} onClick={saveToMedia}>
              {saving ? "Saving…" : "Save to media"}
            </button>
            <button
              type="button"
              className="sp-btn"
              onClick={() => {
                URL.revokeObjectURL(take.url);
                setTake(null);
                uploadedTakeRef.current = null;
                setUploadedTake(null);
                setFinishedTake(null);
              }}
            >
              ✕
            </button>
          </div>
          <div className="ltx-finish">
            <div className="st-title">
              <span className="sp-label">LTX pose finish</span>
              <span className="sp-info">{motionVideoModel ? (take.fullLength ? "2000 cr · 10s" : "1000 cr · 5s") : "not exposed"}</span>
            </div>
            <textarea
              className="sp-prompt"
              rows={2}
              value={enhancePrompt}
              placeholder="Describe the final character, scene, lighting and camera style…"
              onChange={(event) => setEnhancePrompt(event.target.value)}
            />
            <div className="st-row">
              <select className="st-select" value={referenceSheet} onChange={(event) => setReferenceSheet(event.target.value)}>
                <option value="">No identity reference</option>
                {referenceImages.map((object) => (
                  <option key={object.key} value={object.url}>{object.name}</option>
                ))}
              </select>
              <input
                className="st-select"
                type="number"
                min={0}
                step={1}
                value={seed}
                placeholder="Seed (blank = random)"
                onChange={(event) => setSeed(event.target.value)}
              />
            </div>
            <label className="st-row between">
              <span className="sp-info">Pose hold {guideStrength.toFixed(2)}</span>
              <input
                type="range"
                min={0.3}
                max={1}
                step={0.05}
                value={guideStrength}
                onChange={(event) => setGuideStrength(Number(event.target.value))}
              />
            </label>
            <div className="st-row between">
              <span className="sp-info hint">{take.ltxReady ? "IC-LoRA capture profile" : "record in an LTX mode first"}</span>
              <button type="button" className="sp-btn gen" disabled={!motionVideoModel || !take.ltxReady || enhancing} onClick={enhanceTake}>
                {enhancing ? "LTX rendering…" : "Finish motion"}
              </button>
            </div>
            {jobNote && <div className={`sp-info hint job-note${jobNote.startsWith("failed") ? " warn" : ""}`}>{jobNote}</div>}
            {!motionVideoModel && <div className="sp-info hint warn">Pose-controlled enhancement is currently unavailable.</div>}
          </div>
          {finishedTake && (
            <div className="ltx-result">
              <div className="st-title"><span className="sp-label">Finished motion</span><span className="sp-info">queued in Studio</span></div>
              <video src={finishedTake.url} controls autoPlay loop muted />
              <a className="sp-btn" href={finishedTake.url} target="_blank" rel="noreferrer">Open result</a>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
